project_name: crawl-web
description: "Proyecto para archivar/preservar la información de la web Boliviana"
author: Andres Chirinos
created_date: 2025-08-24
version: 1.0.0

data_dir: "data"
output_dir: "output"

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  folder_id: "173yaAeffi9eq2vrARhcJBuCRDOQmUmHv"