project:
  type: website

website:
  title: "Crawl"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



